baseURL = "https://virtual.github.io/speakersmontana/"
languageCode = "en-us"
title = "Showing Up: The Power of Connecting With Each Other and Ourselves"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "UA-131760267-1"

enableGitInfo = true
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/logo.png"

    # Gestion des langues : FR / EN / NL / DE
    [[Params.listeLangues]]
    code = "en"



# Gestion des langues : FR / EN / NL / DE
[Languages]
    

    ############# 2 - Site en TLI Montana
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "Showing Up: The Power of Connecting With Each Other and Ourselves"
    dateFormat = "January 2, 2006"

    home = "Home"
    logo = "images/logos/tli-32.png"
    logotitle = "TLI Montana"
    menufixed = false

    footerDescription = "TLI Montana, a statewide Toastmasters Leadership Institute, is a leadership-focused professional development experience, providing training, community and entertainment to professionals throughout Montana."
    footerSubscribeTitle = "TLI Montana Subscribe"
    footerimg = "images/logos/toastmasters.png"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "Showing Up:<br/><small>The Power of Connecting With Each Other and Ourselves</small>"
        #description = ""
        subtitle = "<span class='tf-ion-android-calendar'><span class='sr-only'>Date</span></span> Saturday, Feb. 2, 2019 <br/><span class='tf-ion-android-time'><span class='sr-only'>Time</span></span> 9:00 AM&ndash;1:30 PM (Doors open 8:30 AM)<br/> <span class='tf-ion-android-pin'><span class='sr-only'>Map</span></span> <a href='https://goo.gl/maps/uNjBYkXcvsL2' target='_blank'>Bozeman Senior Center</a>"
        description = "Compete in a group adventure challenge, network and meet area coaches, listen to inspirational speakers and meet local Toastmasters club members."
        button  = true
        btnText = "Register"
        btnURL  = "https://www.eventbrite.com/e/2019-area-22-23-toastmasters-leadership-institute-tickets-53574271087?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&aff=escb&utm-source=cp&utm-term=listing"
        videoThumb = "images/slider/tli-banner.jpg"
        videoURL   = "https://www.youtube.com/embed/yq93HKHMK6U"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        img = "images/logos/toastmasters-tagline.png"
        title   = "Toastmasters Leadership Institute Professional Development"
        subtitle = "TLI Montana, a statewide Toastmasters Leadership Institute, is a leadership-focused professional development experience, providing training, community and entertainment to professionals throughout Montana.  Kick off 2019 with a bright new spark in your relationships and professional goals! "
        #description = "TLI Montana, a statewide Toastmasters Leadership Institute, is a leadership-focused professional development experience, providing training, community and entertainment to professionals throughout Montana."
        description   = ""

      btnText = "Join our Facebook Group"
        btnURL  = "https://www.facebook.com/groups/TLI.Montana/"
 



    [Languages.en.params.workingprocess]
        enable  = false

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = false
        topTitle= "OUR UNTOLD STORY"
        title   = "TLI Montana Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"


    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "TLI Montana Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "14/05, Stockhome <br> Victori Palace , United States"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        #bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "Kick off 2019 with a bright new spark in your relationships and professional goals!"
        #subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        #btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "register"
        url     = "https://www.eventbrite.com/e/2019-area-22-23-toastmasters-leadership-institute-tickets-53574271087"
        weight  = 3 

 