baseURL = "https://example.org/"
languageCode = "en-us"
title = "TIL Montana | Toastmaster Leadership Institute"
theme = "navigator-hugo"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = true
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
    logo = "images/logo.png"

    # Gestion des langues : FR / EN / NL / DE
    [[Params.listeLangues]]
    code = "en"

# Gestion des langues : FR / EN / NL / DE
[Languages]
    

    ############# 2 - Site en TIL Montana
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "TIL Montana Example site multi-language"
    dateFormat = "January 2, 2006"

    home = "EN Home"
    logo = "images/logo.png"
    menufixed = false

    footerDescription = "TIL Montana Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
    footerServiceTitle = "TIL Montana Service"
    footerQuicklinkTitle = "TIL Montana Quicklinks"
    footerAboutTitle = "TIL Montana About"
    footerSubscribeTitle = "TIL Montana Subscribe"

    # Hero Area Section
    [Languages.en.params.hero]
        enable  = true
        heading = "TIL Montana "
        description = "TLI Montana, a statewide Toastmasters Leadership Institute, is a leadership-focused professional development experience, providing training, community and entertainment to professionals throughout Montana."
        button  = true
        btnText = "Register"
        btnURL  = "https://www.eventbrite.com/e/2019-area-22-23-toastmasters-leadership-institute-tickets-53574271087?utm-medium=discovery&utm-campaign=social&utm-content=attendeeshare&aff=escb&utm-source=cp&utm-term=listing"
        videoThumb = "images/slider/video-player-thumb.jpg"
        videoURL   = "https://www.youtube.com/embed/yq93HKHMK6U"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable  = true
        title   = "TIL Montana We have explored the digital landscape with passion for a long time"
        description = "TLI Montana, a statewide Toastmasters Leadership Institute, is a leadership-focused professional development experience, providing training, community and entertainment to professionals throughout Montana."
 
    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "OUR UNTOLD STORY"
        title   = "TIL Montana Blog."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

    # Contact Section
    [Languages.en.params.contact]
        enable  = true
        topTitle= "DROP US A NOTE"
        title   = "TIL Montana Contact Us."
        subtitle= "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
        address = "14/05, Stockhome <br> Victori Palace , United States"
        phone   = "(03) 9283 2617"
        fax     = "+61 3827 3590"
        facebook= "https://www.facebook.com/"
        twitter = "https://twitter.com/"
        linkedin= "https://www.linkedin.com/"
        dribbble= "https://dribbble.com/"
        instagram= "https://www.instagram.com/"
        mapLatitude = "51.507351"
        mapLongitude= "-0.127758"
        mapMarker   = "images/marker.png"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable  = true
        bg      = "images/call-to-action/call-to-action-bg-2.jpg"
        title   = "TIL Montana Let's Create Something Together"
        subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
        btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "graphicdesign"
        url     = "service"
        weight  = 1
    [[menu.service]]
        name    = "webdesign"
        url     = "service"
        weight  = 2
    [[menu.service]]
        name    = "webdevelopment"
        url     = "service"
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = "partners"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.quicklink]]
        name    = "faqs"
        url     = "about"
        weight  = 3
    [[menu.quicklink]]
        name    = "badges"
        url     = "about"
        weight  = 4
